import * as fs from "fs";
import * as path from "path";

const wsdlDir = path.join(
  __dirname,
  "..",
  "src/infrastructure/outbound/adapters/soap/wsdl"
);

const outputFile = path.join(
  __dirname,
  "..",
  "src/infrastructure/outbound/adapters/soap/wsdl-strings.ts"
);

const files = fs.readdirSync(wsdlDir).filter((f) => f.endsWith(".wsdl"));

let output = `/**
 * WSDL files embedded as strings
 * This file is auto-generated to avoid file system access issues in bundled environments
 * Generated from files in src/infrastructure/outbound/adapters/soap/wsdl/
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: npm run generate:wsdl-strings
 */

export const WSDL_STRINGS: Record<string, string> = {
`;

files.forEach((file) => {
  const content = fs.readFileSync(path.join(wsdlDir, file), "utf8");
  const escaped = content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\${/g, "\\${");
  output += `  '${file}': \`${escaped}\`,\n`;
});

output += `};

export function getWsdlString(filename: string): string | undefined {
  return WSDL_STRINGS[filename];
}
`;

fs.writeFileSync(outputFile, output);
console.log(`✅ Generated wsdl-strings.ts with ${files.length} WSDL files`);
